name: Deploy to EC2

on:
  push:
    branches:
      - main   # auto deploy when code is pushed to main
  workflow_dispatch:   # allows manual trigger from GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH agent
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.233.212.132 '
            set -e
            cd /home/ubuntu/MindTrack---Backend
            git fetch origin
            git reset --hard origin/main
            source venv/bin/activate
            pip install --upgrade -r requirements.txt --no-input
            sudo systemctl restart fastapi
          '
